openapi: "3.0.0"
info:
  version: 1.0.0
  title: sap-test
paths: 
  /defaultResponse:
    get:
      parameters:
        - name: resptype
          in: header
          schema:
            type: string
          example: Example
      responses:
        '200':
          description: Successful response
          content:
            application/xml:
              schema:
                type: object
